from __future__ import annotations

import numpy as np
import os
import torch
from collections.abc import Sequence
from dataclasses import MISSING
from typing import TYPE_CHECKING

from isaaclab.assets import Articulation
from isaaclab.managers import CommandTerm, CommandTermCfg
from isaaclab.markers import VisualizationMarkers, VisualizationMarkersCfg
from isaaclab.markers.config import FRAME_MARKER_CFG
from isaaclab.utils import configclass
from isaaclab.utils.math import (
    matrix_from_quat,
    quat_apply,
    quat_error_magnitude,
    quat_from_euler_xyz,
    quat_inv,
    quat_mul,
    sample_uniform,
    yaw_quat,
)

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnv


class MotionLoader:
    """Load a motion and resolve tracked bodies by name when metadata is available.

    Body indices are not stable across Isaac Sim versions because the URDF importer may
    merge fixed links.  Motion files should therefore contain a ``body_names`` array.
    The legacy ``body_indexes`` argument remains supported for simple replay scripts.
    """

    def __init__(
        self,
        motion_file: str,
        body_indexes: Sequence[int] | None = None,
        device: str = "cpu",
        *,
        body_names: Sequence[str] | None = None,
        runtime_body_names: Sequence[str] | None = None,
    ):
        assert os.path.isfile(motion_file), f"Invalid file path: {motion_file}"
        data = np.load(motion_file)
        self.fps = float(np.asarray(data["fps"]).reshape(-1)[0])
        self.joint_pos = torch.tensor(data["joint_pos"], dtype=torch.float32, device=device)
        self.joint_vel = torch.tensor(data["joint_vel"], dtype=torch.float32, device=device)
        self._body_pos_w = torch.tensor(data["body_pos_w"], dtype=torch.float32, device=device)
        self._body_quat_w = torch.tensor(data["body_quat_w"], dtype=torch.float32, device=device)
        self._body_lin_vel_w = torch.tensor(data["body_lin_vel_w"], dtype=torch.float32, device=device)
        self._body_ang_vel_w = torch.tensor(data["body_ang_vel_w"], dtype=torch.float32, device=device)
        num_motion_bodies = self._body_pos_w.shape[1]

        if body_names is not None:
            if "body_names" in data:
                motion_body_names = [str(name) for name in np.asarray(data["body_names"]).tolist()]
            elif runtime_body_names is not None and num_motion_bodies == len(runtime_body_names):
                # Backward compatibility for files generated by the same runtime before
                # body-name metadata was added.
                motion_body_names = list(runtime_body_names)
            else:
                runtime_count = len(runtime_body_names) if runtime_body_names is not None else "unknown"
                raise ValueError(
                    f"Motion body layout is ambiguous for '{motion_file}': the file contains "
                    f"{num_motion_bodies} bodies, the runtime contains {runtime_count}, and the file "
                    "has no 'body_names' metadata. Re-export or annotate the motion with body names."
                )

            duplicate_names = sorted({name for name in motion_body_names if motion_body_names.count(name) > 1})
            if duplicate_names:
                raise ValueError(f"Duplicate body names in motion file '{motion_file}': {duplicate_names}")

            name_to_index = {name: index for index, name in enumerate(motion_body_names)}
            missing_names = [name for name in body_names if name not in name_to_index]
            if missing_names:
                raise ValueError(f"Motion file '{motion_file}' is missing tracked bodies: {missing_names}")
            resolved_indexes = [name_to_index[name] for name in body_names]
        elif body_indexes is not None:
            resolved_indexes = [int(index) for index in body_indexes]
        else:
            resolved_indexes = list(range(num_motion_bodies))

        if resolved_indexes and max(resolved_indexes) >= num_motion_bodies:
            raise IndexError(
                f"Motion body index {max(resolved_indexes)} exceeds body count {num_motion_bodies} "
                f"in '{motion_file}'."
            )

        self._body_indexes = torch.tensor(resolved_indexes, dtype=torch.long, device=device)
        self.time_step_total = self.joint_pos.shape[0]

    @property
    def body_pos_w(self) -> torch.Tensor:
        return self._body_pos_w[:, self._body_indexes]

    @property
    def body_quat_w(self) -> torch.Tensor:
        return self._body_quat_w[:, self._body_indexes]

    @property
    def body_lin_vel_w(self) -> torch.Tensor:
        return self._body_lin_vel_w[:, self._body_indexes]

    @property
    def body_ang_vel_w(self) -> torch.Tensor:
        return self._body_ang_vel_w[:, self._body_indexes]


class MotionCommand(CommandTerm):
    cfg: MotionCommandCfg

    def __init__(self, cfg: MotionCommandCfg, env: ManagerBasedRLEnv):
        super().__init__(cfg, env)

        self.robot: Articulation = env.scene[cfg.asset_name]
        self.robot_anchor_body_index = self.robot.body_names.index(self.cfg.anchor_body)
        self.motion_anchor_body_index = self.cfg.body_names.index(self.cfg.anchor_body)
        self.body_indexes = torch.tensor(
            self.robot.find_bodies(self.cfg.body_names, preserve_order=True)[0], dtype=torch.long, device=self.device
        )

        self.motion = MotionLoader(
            self.cfg.motion_file,
            device=self.device,
            body_names=self.cfg.body_names,
            runtime_body_names=self.robot.body_names,
        )
        control_fps = 1.0 / float(env.step_dt)
        if not np.isclose(self.motion.fps, control_fps, rtol=0.0, atol=1.0e-3):
            raise ValueError(
                f"Motion FPS ({self.motion.fps:g}) must match the environment control frequency "
                f"({control_fps:g} Hz). Resample the motion before training or playback."
            )
        if cfg.sample_phase_with_episode_horizon and env.max_episode_length > self.motion.time_step_total:
            raise ValueError(
                "Episode length exceeds the motion while horizon-safe phase sampling is enabled: "
                f"{env.max_episode_length} control steps > {self.motion.time_step_total} motion frames. "
                "Use the exact motion duration or a shorter episode."
            )
        self.time_steps = torch.zeros(self.num_envs, dtype=torch.long, device=self.device)
        # Evaluation can opt into holding the final reference frame instead of
        # immediately resampling to a random phase when the motion ends.
        self.freeze_at_motion_end = False
        self.body_pos_relative_w = torch.zeros(self.num_envs, len(cfg.body_names), 3, device=self.device)
        self.body_quat_relative_w = torch.zeros(self.num_envs, len(cfg.body_names), 4, device=self.device)
        self.body_quat_relative_w[:, :, 0] = 1.0

        self.metrics["error_anchor_pos"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_xy"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_rot"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_lin_vel"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_xy_vel"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_anchor_ang_vel"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_body_pos"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_body_rot"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_joint_pos"] = torch.zeros(self.num_envs, device=self.device)
        self.metrics["error_joint_vel"] = torch.zeros(self.num_envs, device=self.device)
        # This remains zero for every horizon-safe episode.  It is deliberately
        # logged as a metric so a motion-boundary regression cannot go unnoticed.
        self.metrics["motion_wrap_count"] = torch.zeros(self.num_envs, device=self.device)

    @property
    def command(self) -> torch.Tensor:  # TODO Consider again if this is the best observation
        # Include the raw (unaligned) reference root pose so policies can directly consume the
        # commanded root state in addition to the DOF targets.
        # root_pos = self.anchor_pos_w
        # root_rot_mat = matrix_from_quat(self.anchor_quat_w)
        # root_rot = root_rot_mat[..., :2].reshape(root_rot_mat.shape[0], -1)
        return torch.cat([self.joint_pos, self.joint_vel], dim=1)

    @property
    def joint_pos(self) -> torch.Tensor:
        return self.motion.joint_pos[self.time_steps]

    @property
    def joint_vel(self) -> torch.Tensor:
        return self.motion.joint_vel[self.time_steps]

    @property
    def body_pos_w(self) -> torch.Tensor:
        return self.motion.body_pos_w[self.time_steps] + self._env.scene.env_origins[:, None, :]

    @property
    def body_quat_w(self) -> torch.Tensor:
        return self.motion.body_quat_w[self.time_steps]

    @property
    def body_lin_vel_w(self) -> torch.Tensor:
        return self.motion.body_lin_vel_w[self.time_steps]

    @property
    def body_ang_vel_w(self) -> torch.Tensor:
        return self.motion.body_ang_vel_w[self.time_steps]

    @property
    def anchor_pos_w(self) -> torch.Tensor:
        return self.motion.body_pos_w[self.time_steps, self.motion_anchor_body_index] + self._env.scene.env_origins

    @property
    def anchor_quat_w(self) -> torch.Tensor:
        return self.motion.body_quat_w[self.time_steps, self.motion_anchor_body_index]

    @property
    def anchor_lin_vel_w(self) -> torch.Tensor:
        return self.motion.body_lin_vel_w[self.time_steps, self.motion_anchor_body_index]

    @property
    def anchor_ang_vel_w(self) -> torch.Tensor:
        return self.motion.body_ang_vel_w[self.time_steps, self.motion_anchor_body_index]

    @property
    def robot_joint_pos(self) -> torch.Tensor:
        return self.robot.data.joint_pos

    @property
    def robot_joint_vel(self) -> torch.Tensor:
        return self.robot.data.joint_vel

    @property
    def robot_body_pos_w(self) -> torch.Tensor:
        return self.robot.data.body_pos_w[:, self.body_indexes]

    @property
    def robot_body_quat_w(self) -> torch.Tensor:
        return self.robot.data.body_quat_w[:, self.body_indexes]

    @property
    def robot_body_lin_vel_w(self) -> torch.Tensor:
        return self.robot.data.body_lin_vel_w[:, self.body_indexes]

    @property
    def robot_body_ang_vel_w(self) -> torch.Tensor:
        return self.robot.data.body_ang_vel_w[:, self.body_indexes]

    @property
    def robot_anchor_pos_w(self) -> torch.Tensor:
        return self.robot.data.body_pos_w[:, self.robot_anchor_body_index]

    @property
    def robot_anchor_quat_w(self) -> torch.Tensor:
        return self.robot.data.body_quat_w[:, self.robot_anchor_body_index]

    @property
    def robot_anchor_lin_vel_w(self) -> torch.Tensor:
        return self.robot.data.body_lin_vel_w[:, self.robot_anchor_body_index]

    @property
    def robot_anchor_ang_vel_w(self) -> torch.Tensor:
        return self.robot.data.body_ang_vel_w[:, self.robot_anchor_body_index]

    def _update_metrics(self):
        anchor_pos_error = self.anchor_pos_w - self.robot_anchor_pos_w
        anchor_lin_vel_error = self.anchor_lin_vel_w - self.robot_anchor_lin_vel_w
        self.metrics["error_anchor_pos"] = torch.norm(anchor_pos_error, dim=-1)
        self.metrics["error_anchor_xy"] = torch.norm(anchor_pos_error[:, :2], dim=-1)
        self.metrics["error_anchor_rot"] = quat_error_magnitude(self.anchor_quat_w, self.robot_anchor_quat_w)
        self.metrics["error_anchor_lin_vel"] = torch.norm(anchor_lin_vel_error, dim=-1)
        self.metrics["error_anchor_xy_vel"] = torch.norm(anchor_lin_vel_error[:, :2], dim=-1)
        self.metrics["error_anchor_ang_vel"] = torch.norm(self.anchor_ang_vel_w - self.robot_anchor_ang_vel_w, dim=-1)

        self.metrics["error_body_pos"] = torch.norm(self.body_pos_relative_w - self.robot_body_pos_w, dim=-1).mean(
            dim=-1
        )
        self.metrics["error_body_rot"] = quat_error_magnitude(self.body_quat_relative_w, self.robot_body_quat_w).mean(
            dim=-1
        )

        self.metrics["error_body_lin_vel"] = torch.norm(self.body_lin_vel_w - self.robot_body_lin_vel_w, dim=-1).mean(
            dim=-1
        )
        self.metrics["error_body_ang_vel"] = torch.norm(self.body_ang_vel_w - self.robot_body_ang_vel_w, dim=-1).mean(
            dim=-1
        )

        self.metrics["error_joint_pos"] = torch.norm(self.joint_pos - self.robot_joint_pos, dim=-1)
        self.metrics["error_joint_vel"] = torch.norm(self.joint_vel - self.robot_joint_vel, dim=-1)

    def _resample_command(self, env_ids: Sequence[int]):
        if self.cfg.sample_phase_with_episode_horizon:
            # Sample only phases from which the configured episode can reach
            # its time limit without wrapping the motion or teleporting the
            # robot to a new random phase.  This preserves the source root XY
            # trajectory while enabling genuinely long contiguous rollouts.
            horizon_steps = min(int(self._env.max_episode_length), self.motion.time_step_total)
            max_start_step = max(self.motion.time_step_total - horizon_steps, 0)
            self.time_steps[env_ids] = torch.randint(
                low=0,
                high=max_start_step + 1,
                size=(len(env_ids),),
                device=self.device,
            )
        else:
            phase = sample_uniform(0.0, 1.0, (len(env_ids),), device=self.device)
            self.time_steps[env_ids] = (phase * (self.motion.time_step_total - 1)).long()

        root_pos = self.body_pos_w[:, 0].clone()
        root_ori = self.body_quat_w[:, 0].clone()
        root_lin_vel = self.body_lin_vel_w[:, 0].clone()
        root_ang_vel = self.body_ang_vel_w[:, 0].clone()

        range_list = [self.cfg.pose_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
        ranges = torch.tensor(range_list, device=self.device)
        rand_samples = sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=self.device)
        root_pos[env_ids] += rand_samples[:, 0:3]
        orientations_delta = quat_from_euler_xyz(rand_samples[:, 3], rand_samples[:, 4], rand_samples[:, 5])
        root_ori[env_ids] = quat_mul(orientations_delta, root_ori[env_ids])
        range_list = [self.cfg.velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
        ranges = torch.tensor(range_list, device=self.device)
        rand_samples = sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=self.device)
        root_lin_vel[env_ids] += rand_samples[:, :3]
        root_ang_vel[env_ids] += rand_samples[:, 3:]

        joint_pos = self.joint_pos.clone()
        joint_vel = self.joint_vel.clone()

        joint_pos += sample_uniform(*self.cfg.joint_position_range, joint_pos.shape, joint_pos.device)
        soft_joint_pos_limits = self.robot.data.soft_joint_pos_limits[env_ids]
        joint_pos[env_ids] = torch.clip(
            joint_pos[env_ids], soft_joint_pos_limits[:, :, 0], soft_joint_pos_limits[:, :, 1]
        )
        self.robot.write_joint_state_to_sim(joint_pos[env_ids], joint_vel[env_ids], env_ids=env_ids)
        self.robot.write_root_state_to_sim(
            torch.cat([root_pos[env_ids], root_ori[env_ids], root_lin_vel[env_ids], root_ang_vel[env_ids]], dim=-1),
            env_ids=env_ids,
        )

    def _update_command(self):
        if self.cfg.sample_phase_with_episode_horizon:
            # ManagerBasedRLEnv resets timed-out environments before the command
            # manager is computed.  Their episode counter is therefore zero here,
            # and advancing them would silently skip the freshly sampled frame.
            # Non-reset environments advance exactly once per control step.
            advance_mask = self._env.episode_length_buf > 0
            self.time_steps[advance_mask] += 1
        else:
            self.time_steps += 1
        if self.freeze_at_motion_end:
            self.time_steps.clamp_(max=self.motion.time_step_total - 1)
            self.refresh_reference_alignment()
            return
        env_ids = torch.where(self.time_steps >= self.motion.time_step_total)[0]
        if self.cfg.sample_phase_with_episode_horizon and len(env_ids) > 0:
            self.metrics["motion_wrap_count"][env_ids] += 1.0
            first_env = int(env_ids[0].item())
            first_step = int(self.time_steps[first_env].item())
            raise RuntimeError(
                "Horizon-safe motion sampling reached the end of the motion before episode reset "
                f"(env={first_env}, step={first_step}, motion_frames={self.motion.time_step_total}). "
                "This would wrap the reference trajectory and is forbidden."
            )
        self._resample_command(env_ids)

        self.refresh_reference_alignment()

    def refresh_reference_alignment(self):
        """Refresh aligned body targets without advancing the motion frame."""
        anchor_pos_w_repeat = self.anchor_pos_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)
        anchor_quat_w_repeat = self.anchor_quat_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)
        robot_anchor_pos_w_repeat = self.robot_anchor_pos_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)
        robot_anchor_quat_w_repeat = self.robot_anchor_quat_w[:, None, :].repeat(1, len(self.cfg.body_names), 1)

        delta_pos_w = robot_anchor_pos_w_repeat
        delta_pos_w[..., 2] = anchor_pos_w_repeat[..., 2]
        delta_ori_w = yaw_quat(quat_mul(robot_anchor_quat_w_repeat, quat_inv(anchor_quat_w_repeat)))

        self.body_quat_relative_w = quat_mul(delta_ori_w, self.body_quat_w)
        self.body_pos_relative_w = delta_pos_w + quat_apply(delta_ori_w, self.body_pos_w - anchor_pos_w_repeat)

    def _set_debug_vis_impl(self, debug_vis: bool):
        if debug_vis:
            if not hasattr(self, "current_anchor_visualizer"):
                self.current_anchor_visualizer = VisualizationMarkers(
                    self.cfg.anchor_visualizer_cfg.replace(prim_path="/Visuals/Command/current/anchor")
                )
                self.goal_anchor_visualizer = VisualizationMarkers(
                    self.cfg.anchor_visualizer_cfg.replace(prim_path="/Visuals/Command/goal/anchor")
                )

                self.current_body_visualizers = []
                self.goal_body_visualizers = []
                for name in self.cfg.body_names:
                    self.current_body_visualizers.append(
                        VisualizationMarkers(
                            self.cfg.body_visualizer_cfg.replace(prim_path="/Visuals/Command/current/" + name)
                        )
                    )
                    self.goal_body_visualizers.append(
                        VisualizationMarkers(
                            self.cfg.body_visualizer_cfg.replace(prim_path="/Visuals/Command/goal/" + name)
                        )
                    )

            self.current_anchor_visualizer.set_visibility(True)
            self.goal_anchor_visualizer.set_visibility(True)
            for i in range(len(self.cfg.body_names)):
                self.current_body_visualizers[i].set_visibility(True)
                self.goal_body_visualizers[i].set_visibility(True)

        else:
            if hasattr(self, "current_anchor_visualizer"):
                self.current_anchor_visualizer.set_visibility(False)
                self.goal_anchor_visualizer.set_visibility(False)
                for i in range(len(self.cfg.body_names)):
                    self.current_body_visualizers[i].set_visibility(False)
                    self.goal_body_visualizers[i].set_visibility(False)

    def _debug_vis_callback(self, event):
        if not self.robot.is_initialized:
            return

        self.current_anchor_visualizer.visualize(self.robot_anchor_pos_w, self.robot_anchor_quat_w)
        self.goal_anchor_visualizer.visualize(self.anchor_pos_w, self.anchor_quat_w)

        for i in range(len(self.cfg.body_names)):
            self.current_body_visualizers[i].visualize(self.robot_body_pos_w[:, i], self.robot_body_quat_w[:, i])
            self.goal_body_visualizers[i].visualize(self.body_pos_relative_w[:, i], self.body_quat_relative_w[:, i])


@configclass
class MotionCommandCfg(CommandTermCfg):
    """Configuration for the motion command."""

    class_type: type = MotionCommand

    asset_name: str = MISSING

    motion_file: str = MISSING
    anchor_body: str = MISSING
    body_names: list[str] = MISSING

    pose_range: dict[str, tuple[float, float]] = {}
    velocity_range: dict[str, tuple[float, float]] = {}

    joint_position_range: tuple[float, float] = (-0.52, 0.52)

    sample_phase_with_episode_horizon: bool = False
    """Keep sampled motion phases far enough from the end for one full episode."""

    anchor_visualizer_cfg: VisualizationMarkersCfg = FRAME_MARKER_CFG.replace(prim_path="/Visuals/Command/pose")
    anchor_visualizer_cfg.markers["frame"].scale = (0.2, 0.2, 0.2)

    body_visualizer_cfg: VisualizationMarkersCfg = FRAME_MARKER_CFG.replace(prim_path="/Visuals/Command/pose")
    body_visualizer_cfg.markers["frame"].scale = (0.1, 0.1, 0.1)
